# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Education
    url: '#about'
    weight: 20
  - name: Publications
    url: '#publications'
    weight: 30
  - name: Scholarships
    url: '#projects'
    weight: 40
  - name: Conferences
    url: '#talks'
    weight: 50
  - name: Collaborations
    url: '#featured'
    weight: 60
  - name: Training
    url: '#posts'
    weight: 70
  - name: Gallery
    url: '#gallery'
    weight: 80
  - name: Contact
    url: '#contact'
    weight: 90
